# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: telebit-client
    main: ./cmd/telebit/telebit.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: telebit-mgmt
    main: ./cmd/mgmt/mgmt.go
    binary: telebit-mgmt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      386: i386
      amd64: x86_64
      arm64: aarch64
    format_overrides:
      - goos: windows
        format: zip
env_files:
  github_token: ~/.config/goreleaser/github_token.txt
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
